---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command run augenrules'
  command: "{{command_cmd_run_augenrules}}"

- name: 'command restart auditd'
  command: "{{command_cmd_restart_auditd}}"
  args:
    warn: 'false'
