---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - install
    - passwd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file ensure passwd'
  file:
    state: 'file'
    dest: "{{file_dst_passwd}}"
    mode: "{{file_mode_passwd}}"
    owner: "{{file_owner_passwd}}"
    group: "{{file_group_passwd}}"
  tags:
    - install
    - passwd
