---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - remove
    - vim

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove vim'
  package:
    state: 'absent'
    name: "{{package_name_vim}}"
    install_recommends: 'no'
  tags:
    - remove
    - vim

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove vimrc'
  file:
    state: 'absent'
    path: "{{file_dst_vimrc}}"
  tags:
    - remove
    - vim
