---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - install
    - mailx

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install mailx'
  package:
    state: 'present'
    name: "{{package_name_mailx}}"
    install_recommends: 'no'
  tags:
    - install
    - mailx
