---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - install
    - issue

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create issue'
  template:
    src: "{{file_src_issue}}"
    dest: "{{file_dst_issue}}"
    mode: "{{file_mode_issue}}"
    owner: "{{file_owner_issue}}"
    group: "{{file_group_issue}}"
  tags:
    - install
    - issue
