---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_major_version}}.yml"
      - 'vars/main.yml'
      errors: 'ignore'
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'group create node_exporter'
  group:
    state: 'present'
    name: "{{group_name_node_exporter}}"
    system: "{{group_system_node_exporter}}"
  tags:
    - install
    - node_exporter

- name: 'user create node_exporter'
  user:
    state: 'present'
    name: "{{user_name_node_exporter}}"
    comment: "{{user_comment_node_exporter}}"
    group: "{{user_group_node_exporter}}"
    append: "{{user_append_node_exporter}}"
    createhome: "{{user_home_create_node_exporter}}"
    move_home: "{{user_home_move_node_exporter}}"
    remove: "{{user_home_remove_node_exporter}}"
    force: "{{user_home_force_node_exporter}}"
    password: "{{user_password_node_exporter}}"
    update_password: "{{user_password_update_node_exporter}}"
    shell: "{{user_shell_node_exporter}}"
    system: "{{user_system_node_exporter}}"
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create node_exporter_app.dir'
  file:
    state: 'directory'
    path: "{{file_dst_node_exporter_app_dir}}"
    mode: "{{file_mode_node_exporter_app_dir}}"
    owner: "{{file_owner_node_exporter_app_dir}}"
    group: "{{file_group_node_exporter_app_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create node_exporter_bin.dir'
  file:
    state: 'directory'
    path: "{{file_dst_node_exporter_bin_dir}}"
    mode: "{{file_mode_node_exporter_bin_dir}}"
    owner: "{{file_owner_node_exporter_bin_dir}}"
    group: "{{file_group_node_exporter_bin_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create node_exporter_data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_node_exporter_data_dir}}"
    mode: "{{file_mode_node_exporter_data_dir}}"
    owner: "{{file_owner_node_exporter_data_dir}}"
    group: "{{file_group_node_exporter_data_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create textfile_collector.dir'
  file:
    state: 'directory'
    path: "{{file_dst_textfile_collector_dir}}"
    mode: "{{file_mode_textfile_collector_dir}}"
    owner: "{{file_owner_textfile_collector_dir}}"
    group: "{{file_group_textfile_collector_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file download node_exporter.tar.gz'
  get_url:
    url: "{{file_src_node_exporter_tar_gz}}"
    dest: "{{file_dst_node_exporter_tar_gz}}"
    mode: "{{file_mode_node_exporter_tar_gz}}"
    owner: "{{file_owner_node_exporter_tar_gz}}"
    group: "{{file_group_node_exporter_tar_gz}}"
    checksum: "{{node_exporter_checksum_algorithm}}:{{node_exporter_checksum}}"
  tags:
    - install
    - node_exporter

- name: 'file unarchive node_exporter'
  unarchive:
    src: "{{file_src_node_exporter}}"
    dest: "{{file_dst_node_exporter}}"
    owner: "{{file_owner_node_exporter}}"
    group: "{{file_group_node_exporter}}"
    creates: "{{file_creates_node_exporter}}"
    remote_src: 'yes'
  tags:
    - install
    - node_exporter

- name: 'file create node_exporter.service'
  template:
    src: "{{file_src_node_exporter_service}}"
    dest: "{{file_dst_node_exporter_service}}"
    mode: "{{file_mode_node_exporter_service}}"
    owner: "{{file_owner_node_exporter_service}}"
    group: "{{file_group_node_exporter_service}}"
  notify: 'command systemctl daemon-reload'
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# META
#-------------------------------------------------------------------------------

- name: 'meta flush handlers'
  meta: 'flush_handlers'
  tags:
    - install
    - node_exporter
