---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - disable
    - hddtemp

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create hddtemp'
  template:
    src: "{{file_src_hddtemp}}"
    dest: "{{file_dst_hddtemp}}"
    mode: "{{file_mode_hddtemp}}"
    owner: "{{file_owner_hddtemp}}"
    group: "{{file_group_hddtemp}}"
  tags:
    - disable
    - hddtemp

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service stop hddtemp'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_hddtemp}}"
  tags:
    - disable
    - hddtemp
