---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - enable
    - systemd_timesyncd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create timesyncd.conf'
  template:
    src: "{{file_src_timesyncd_conf}}"
    dest: "{{file_dst_timesyncd_conf}}"
    mode: "{{file_mode_timesyncd_conf}}"
    owner: "{{file_owner_timesyncd_conf}}"
    group: "{{file_group_timesyncd_conf}}"
  notify: 'service restart systemd-timesyncd'
  tags:
    - enable
    - systemd_timesyncd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start systemd-timesyncd'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_systemd_timesyncd}}"
  tags:
    - enable
    - systemd_timesyncd
